### ISSUE TITLE
Registration failure message unclear

### ISSUE THREAD

**Issue by ihayet** [Hyptastic/ProjectXAndroid#47]
1. Duplicate email or duplicate contact number's error message should be clear. e.g. "This email address is already in use. Please try with a different email address."

**Comment by saadmanfarhad** [comment]
Changed it..but cannot differentiate between duplicate email and contact number because both return same status code

**Comment by ihayet** [comment]
Okay. Please check if there is any scope for parsing the error message on the server side, to narrow down on the problem. However, it should do for now.
